[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "test-actions"
authors = [{ name = "Dimitri RODARIE", email = "d.rodarie@gmail.com" }]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = ["License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"]
requires-python = ">=3.9"
dynamic = ["version", "description"]
dependencies = [
    "numpy~=1.19",
    "scipy~=1.5",
    "pynrrd~=1.0",
    "toml~=0.10.0",
]

[project.optional-dependencies]
test = [
    "coverage~=7.3",
]
dev = [
    "pre-commit~=3.5",
    "black~=24.0",
    "isort~=5.12"
]

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
