name: Ruff

on:
  push:
    branches:
      - '**'  # matches every branch ...
      - '!main'  # ... that is not main

jobs:
  ruff:
    uses: ./.github/workflows/ruff.yml
  build:
    uses: ./.github/workflows/build.yml
