name: Create release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check tag branch
        uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "main"
          tag: "${{ github.ref_name }}"
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        shell: bash
        run: |
          if [[ ${{ steps.contains_tag.outputs.retval }} == 'true' ]]; then
            gh release create "$tag" \
                  --repo="$GITHUB_REPOSITORY" \
                  --title="$tag" \
                  --generate-notes
          fi
