name: Bump version, create release and deploy

on:
  push:
    branches:
      - main

jobs:
  bump:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semver.outputs.next }}
      old_tag: ${{ steps.semver.outputs.current }}
    environment: codegen
    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Bump version in Python project
        run: |
          pip install --upgrade pip bump-my-version
          oldv="${{ steps.semver.outputs.current }}"
          newv="${{steps.semver.outputs.next}}"
          # Bump the version, dropping the leading `v` with `${x:1}`
          bump-my-version replace --current-version=${oldv:1} --new-version=${newv:1} pyproject.toml

      - name: Commit & Push changes
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git commit -am "docs: bump version: ${{ steps.semver.outputs.current }} → ${{ steps.semver.outputs.next }}"
          git push origin main

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semver.outputs.next }}
          github_token: ${{ steps.app-token.outputs.token }}

  release:
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Pull commit of tag update
        run: |
          git pull origin main 

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ needs.bump.outputs.tag }}
          toTag: ${{ needs.bump.outputs.old_tag }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ needs.bump.outputs.tag }}
          name: ${{ needs.bump.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ github.token }}

      - name: Commit CHANGELOG.md
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git commit -am 'docs: update CHANGELOG.md for ${{ github.ref_name }}'
          git push origin main

  deploy:
    runs-on: ubuntu-latest
    needs: release

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m build
          twine upload --verbose --repository testpypi dist/*
