name: Build, test, deploy

on:
  push:
    branches:
      - main


jobs:
  ruff:
    uses: ./.github/workflows/ruff.yml
  build:
    uses: ./.github/workflows/build.yml

  bump:
    needs: [ruff, build]
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.semver.outputs.next }}
      old_tag: ${{ steps.semver.outputs.current }}

    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          branch: main
          noVersionBumpBehavior: warn

  tag_release:
    needs: [bump]
    if: ${{ needs.bump.outputs.tag != ''}}
    runs-on: ubuntu-latest
    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Bump version in Python project
        run: |
          pip install --upgrade pip bump-my-version
          oldv="${{ needs.bump.outputs.old_tag }}"
          newv="${{needs.bump.outputs.tag}}"
          # Bump the version, dropping the leading `v` with `${x:1}`
          bump-my-version replace --current-version=${oldv:1} --new-version=${newv:1} pyproject.toml

      - name: Commit & Push version change
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: bump version: ${{ needs.bump.outputs.old_tag }} → ${{ needs.bump.outputs.tag }} [skip ci]'

      - name: Create tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ needs.bump.outputs.tag }}
          github_token: ${{ steps.app-token.outputs.token }}

  release:
    runs-on: ubuntu-latest
    needs: [bump, tag_release]

    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Pull commit of version change
        run: |
          git pull origin main 

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          fromTag: ${{ needs.bump.outputs.tag }}
          toTag: ${{ needs.bump.outputs.old_tag }}

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          tag: ${{ needs.bump.outputs.tag }}
          name: ${{ needs.bump.outputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md

  pypi-publish:
    runs-on: ubuntu-latest
    needs: release
    environment:
      name: testpypi
      url: https://test.pypi.org/p/drodarie_test_actions
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Create Github token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Pull commits of version bump
        run: |
          git pull origin main

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: |
          uv build

      - name: Publish package distributions to Test.PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
