name: Validate Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

env:
  LOCAL_PR: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
  TEST_TRIGGER: ${{ github.event.action == 'synchronize' || github.event.action == 'opened' || github.event.action == 'reopened'}}

jobs:
  variables:  # env variables are not accessible through job.if (https://stackoverflow.com/q/73558652)
    runs-on: ubuntu-latest
    outputs:
      LOCAL_PR: ${{ steps.init.outputs.LOCAL_PR }}
      TEST_TRIGGER: ${{ steps.init.outputs.TEST_TRIGGER }}
    steps:
      - name: Make environment variables global
        id: init
        run: |
          echo "LOCAL_PR=${{ env.LOCAL_PR }}" >> $GITHUB_OUTPUT
          echo "TEST_TRIGGER=${{ env.TEST_TRIGGER }}" >> $GITHUB_OUTPUT

  isort:
    needs: variables
    # if PR is external, trigger the tests on push or new PR
    if: ${{ needs.variables.outputs.LOCAL_PR == 'false' && needs.variables.outputs.TEST_TRIGGER == 'true' }}
    uses: ./.github/workflows/isort.yml
  black:
    needs: variables
    if: ${{ needs.variables.outputs.LOCAL_PR == 'false' && needs.variables.outputs.TEST_TRIGGER == 'true' }}
    uses: ./.github/workflows/black.yml
  build:
    needs: variables
    if: ${{ needs.variables.outputs.LOCAL_PR == 'false' && needs.variables.outputs.TEST_TRIGGER == 'true' }}
    uses: ./.github/workflows/build.yml
  validate-pr-title:
    needs: variables
    # Trigger only for local PR when PR is edited (title, description, etc.)
    if: ${{ needs.variables.outputs.LOCAL_PR == 'true' && github.event.action == 'edited' }}
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@1.2.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","revert"]'
