name: PR Conventional Commit Validation

on: [pull_request]

jobs:
  isort:
    uses: ./.github/workflows/isort.yml
  black:
    uses: ./.github/workflows/black.yml
  build:
    uses: ./.github/workflows/build.yml

  validate-pr-title:
    runs-on: ubuntu-latest
    if: github.event.action == 'opened' || github.event.action == 'synchronized' || github.event.action == 'reopened' || github.event.action == 'edited'
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@1.2.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","revert"]'