name: PR Conventional Commit Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  isort:
    if: github.event.action != 'edited'
    uses: ./.github/workflows/isort.yml
  black:
    if: github.event.action != 'edited'
    uses: ./.github/workflows/black.yml
  build:
    if: github.event.action != 'edited'
    uses: ./.github/workflows/build.yml

  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@1.2.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","revert"]'